name: Test and Deploy
on:
push:
    branches: [ main ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    with:
        node-version: 16.x
    - run: npm ci
    - run: npm test

